version: 0.1

phases:
  build:
    commands:
      - "echo resolved source version: $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - "echo source version: $CODEBUILD_SOURCE_VERSION"
      - make codebuild-docker-push
      - cd wsf-web-scraper && make codebuild-docker-push

artifacts:
    files: []
